### PR TITLE
Issue #83: Fixed redirect so a user can only access the auth page

### LINKED ISSUE #83: During the auth login flow you must not be able to go to the prefs page
ie only allow the prefs page if you are in the gracemode fallback step

### PR DESCRIPTION
**Pull request by Peterburnett**
Closes #83

### CODE REVIEW

File: lib.php [hunk 1]
```diff
@@ -46,7 +46,7 @@ function tool_mfa_after_require_login() {
 
         $clearurl = str_replace($CFG->wwwroot, '', $ME);
 
-        if (strpos($clearurl, '/admin/tool/mfa/') !== 0) {
+        if (strpos($clearurl, '/admin/tool/mfa/auth.php') !== 0) {
```
Comment (brendanheywood) [inline lib.php]: Can you please move the wantsurl logic down into here, we should only set it if we do end up actually redirecting

Can you also please refactor this into a 'should_redirect($url)' method and wrap some unit tests around it.

Right now the logic is simple but its going to get more complex. As a starting point hack you account so that user_not_fully_set_up() returns false which will try to redirect you to edit your profile before this callback fires, which will then start an infinite redirect loop here

Comment (brendanheywood) [reply lib.php]: Other tests:
* if you are AJAX never redirect
* if you are a webservice all never redirect

File: factor/grace/classes/factor.php [hunk 2]
```diff
@@ -45,7 +45,7 @@ public function get_all_user_factors() {
         if (!empty($records)) {
             return $records;
         }
-        
+
```
Comment (brendanheywood) [inline factor/grace/classes/factor.php]: cleanup
