### PR TITLE
Issue #148: Fixed error with redirect loop explosions

### LINKED ISSUE #148: Unsupported redirect detected, script execution terminated when logging in.
After installing this plugin, turning ip range factor on and setting an address, when trying to login I get the following error which prevents access to the site. (using Moodle master code from today.) 

Unsupported redirect detected, script execution
Stack trace:
line 478 of /admin/tool/mfa/classes/manager.php: moodle_exception thrown
line 41 of /admin/tool/mfa/lib.php: call to tool_mfa\manager::require_auth()
line 2825 of /lib/moodlelib.php: call to tool_mfa_after_require_login()
line 31 of /admin/tool/mfa/auth.php: call to require_login()
×Output buffer: <div class="notifytiny debuggingmessage" data-rel="debugging">Exception calling 'tool_mfa_after_config'<ul style="text-align: left" data-rel="backtrace"><li>line 87 of /admin/tool/mfa/lib.php: call to tool_mfa\manager::require_auth()</li><li>line 1054 of /lib/setup.php: call to tool_mfa_after_config()</li><li>line 109 of /config.php: call to require_once()</li><li>line 25 of /admin/tool/mfa/auth.php: call to require_once()</li></ul></div>

### LINKED ISSUE #155: Fix travis postgres error

### PR DESCRIPTION
**Pull request by Peterburnett**
Closes #148, can no longer reproduced locally, where issue is caused by sitepolicy checks, when define isn't set. Also closes #155 as Travis needed to be green for this PR

### CODE REVIEW

File: classes/manager.php [hunk 1]
```diff
@@ -464,7 +468,15 @@ public static function require_auth($courseorid = null, $autologinguest = null,
 
         if (empty($SESSION->tool_mfa_authenticated) || !$SESSION->tool_mfa_authenticated) {
             $cleanurl = new \moodle_url($ME);
+            $authurl = new \moodle_url('/admin/tool/mfa/auth.php');
+
             $redir = self::should_require_mfa($cleanurl, $preventredirect);
+
+            if ($redir == self::NO_REDIRECT && !$cleanurl->compare($authurl)) {
+                // A non-MFA page that should take precedence.
```
Comment (brendanheywood) [inline classes/manager.php]: can you flesh this out into a paragraph of what pending mode is
