### PR TITLE
Issue #280: Added debug output to the auth fail screen

### LINKED ISSUE #280: Show debug mode on the Failed auth page if enabled
It will not give significant info on passing factors, but allows viewing the config and seeing the ordering and flow of factors.

### PR DESCRIPTION
**Pull request by Peterburnett**
Closes #280

### CODE REVIEW

File: classes/manager.php [hunk 1]
```diff
@@ -186,6 +186,9 @@ public static function cannot_login() {
         $renderer = $PAGE->get_renderer('tool_mfa');
 
         echo $renderer->header();
+        if (get_config('tool_mfa', 'debugmode')) {
+            self::display_debug_notification();
```
Comment (brendanheywood) [inline classes/manager.php:190]: hhmm, it makes me thing display_debug_notification should return the html?
