### PR TITLE
Fix class name for base factor tests

### LINKED ISSUE #394: Unit testing is failing due to class names clash
Unit testing is failing due to class names clash

```
root@43c84899593c:/var/www/tabor# vendor/bin/phpunit --testsuite='tool_mfa_testsuite'
Moodle 4.1.3+ (Build: 20230526), 703ca16ec057605e55f62280524ea39049fc2a7c
Php: 7.4.33, mysqli: 5.7.41, OS: Linux 5.15.0-69-generic x86_64

Fatal error: Cannot declare class tool_mfa\tests\manager_test, because the name is already in use in /var/www/tabor/admin/tool/mfa/tests/object_factor_base_test.php on line 28

```

This looks to be a regression of https://github.com/catalyst/moodle-tool_mfa/commit/cc850a7680abfd90ec69dbaf6a3499703598e619

### PR DESCRIPTION
**Pull request by golenkovm**
This resolves #394

### CODE REVIEW

File: tests/object_factor_base_test.php [hunk 1]
```diff
@@ -25,7 +25,7 @@
  * @copyright   2023 Catalyst IT
  * @license     http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
  */
-class manager_test extends tool_mfa_testcase {
+class base_factor_test extends tool_mfa_testcase {
```
Comment (dmitriim) [inline tests/object_factor_base_test.php:28]: should it match file name or vice versa? 
So either class should be object_factor_base_test or file should be base_factor_test.php

Comment (golenkovm) [reply tests/object_factor_base_test.php]: Fixed
