### PR TITLE
Changed error page to allow for state changes in factors

### LINKED ISSUE #211: Bugs with lang strings on failed mfa check
/admin/tool/mfa/auth.php

You are logged in as Brendan Heywood
[[pluginname]]

image

### PR DESCRIPTION
**Pull request by Peterburnett**
Closes #211

### CODE REVIEW

File: auth.php [hunk 1]
```diff
@@ -37,6 +37,14 @@
 $pagetitle = $SITE->shortname.': '.get_string('mfa', 'tool_mfa');
 $PAGE->set_title($pagetitle);
 
+// The only page action allowed here is a logout if it was requested.
+$logout = optional_param('logout', false, PARAM_BOOL);
+if ($logout) {
+    \tool_mfa\manager::mfa_logout();
+    // Now redirect home.
+    redirect(new \moodle_url($CFG->wwwroot));
```
Comment (brendanheywood) [inline auth.php:45]: Would it be possible to redirect back to the original wants url? so that after the second loop through you still end up in the right place

Comment (Peterburnett) [reply auth.php:45]: Ah thats a nice feature.
